### ISSUE TITLE
是否要把 codesniffer 的 package 加在這裡的 composer.json ?

### ISSUE THREAD

**Issue by asika32764** [smstw/sms-php-code-sniffer#1]

**Comment by LeoOnTheEarth** [comment]
安裝 CodeSniffer 進來的話有什麼目的嗎?

**Comment by asika32764** [comment]
直接從專案內執行 phpcs script

Leo notifications@github.com 於 2014年10月1日星期三寫道：

> 安裝 CodeSniffer 進來的話有什麼目的嗎?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smstw/sms-php-code-sniffer/issues/1#issuecomment-57342595
> .

## 

Best Regard

## Simon Asika | Kwang Po Tung | 董冠伯
- Founder: Asikart Extension http://ext.asikart.com/
- CTO: SMS Taiwan http://www.bm-sms.com.tw/
- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by LeoOnTheEarth** [comment]
直接執行是用 `/vendor/bin/phpcs` 嗎?
如果直接這樣用的話是讀不到 `sms-php-code-sniffer` 的
有個前置作業要作
https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-installed-standard-paths

手動打個 command 是可以解決啦，但可以自動話是最好的

目前我在寫 https://github.com/smstw/sms-dev 的時候有想過把這個前置作業自動化
可能會在本專案中加個 Script 檔讓 compsoer 去執行即可

**Comment by LeoOnTheEarth** [comment]
把 CodeSniffer 加進來我覺得無坊
只要知道怎麼使用就沒什麼大問題
有需要的話麻煩你幫忙發個 PR 吧~

**Comment by asika32764** [comment]
我再用devsite 來測試

Leo notifications@github.com 於 2014年10月1日星期三寫道：

> 把 CodeSniffer 加進來我覺得無坊
> 只要知道怎麼使用就沒什麼大問題
> 有需要的話麻煩你幫忙發個 PR 吧~
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smstw/sms-php-code-sniffer/issues/1#issuecomment-57350069
> .

## 

Best Regard

## Simon Asika | Kwang Po Tung | 董冠伯
- Founder: Asikart Extension http://ext.asikart.com/
- CTO: SMS Taiwan http://www.bm-sms.com.tw/
- Mobile: 886-928-565-747
- Github: https://github.com/asika32764

**Comment by LeoOnTheEarth** [comment]
後來還是決定不 require phpcs 進來了
請看下面兩個 commit
https://github.com/smstw/sms-dev/commit/d4ff5ff63be10f7c2d382fd8a2159dfdadb79453
https://github.com/smstw/sms-dev/commit/7e953b6ad699c9532cb7f71fcbe5acc02843337a

**Comment by LeoOnTheEarth** [comment]
好像還有別的方式可以做
我再試試看

**Comment by LeoOnTheEarth** [comment]
解決了，目前該專案直接 clone 回去並做 `composer install` 之後，使用 `vender/bin/phpcs` 可以使用到該專案的 Code Sniffer

若是在其他的專案 require 此 Code Sniffer 的話，要在 composer.json 中加入這段

``` js
"scripts": {
    "post-install-cmd": [
        "php vendor/smstw/php-code-sniffer/scripts/sms-phpcs-init"
    ],
    "post-update-cmd": [
        "php vendor/smstw/php-code-sniffer/scripts/sms-phpcs-init"
    ]
}
```

這樣 `composer install` 或是 `composer update` 都可以正常地把 Code Sniffer 的路徑加進去

**Comment by LeoOnTheEarth** [comment]
這是 windows 上較可行的做法，而且可以相容 OSX 和 Linux
有種做法是直接使用 `vendor/bin/sms-phpcs-init` 但是在 windows 是不能執行的 =_=
除非用 `cmd \c vendor/bin/sms-phpcs-init.bat`，但是這就不能跨平台了
目前直接使用 php 執行是最佳解

**Comment by LeoOnTheEarth** [comment]
https://github.com/smstw/sms-php-code-sniffer/pull/2
composer.json 的支援以這個 PR 為主

**Comment by LeoOnTheEarth** [comment]
closed by PR #2
